name: Tests Code Coverage

jobs:
  tests-jest-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Update composer
        run: composer update

      - name: Run Tests
        run: yarn test

      #- name: Run tests
      #  run: XDEBUG_MODE=coverage vendor/bin/phpunit  --coverage-clover coverage.xml

      - name: Code Coverage upload
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/clover.xml # optional

